/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.netsugo.cpabe.cli;

import com.github.netsugo.cpabe.Cpabe2;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class AppTest {
    @Test
    public void testEncDecSuccess() throws Exception {
        var plain = "Hello";
        var attr = "alice";
        var policy = "bob alice 1of2";

        var setup = Cpabe2.setup();

        var master = setup.master;
        var pubkey = setup.pubkey;
        var secret = Cpabe2.keygen(pubkey, master, attr);

        var encrypted = Cpabe2.encrypt(pubkey, policy, plain.getBytes());
        var decrypted = Cpabe2.decrypt(pubkey, secret, encrypted);
        var result = new String(decrypted);

        assertEquals(plain, result);
    }
}
